language: python
python:
- '3.6'
before_script:
- yes | python setup.py install
- git clone https://github.com/uc-cdis/dictionaryutils; cd dictionaryutils
script:
- "./run_tests.sh"
deploy:
  provider: s3
  access_key_id: AKIAZRNPHKJIJU73ZJ5J
  secret_access_key:
    secure: R5L/u0QCmXm1+3pDqbG3tVMrnLaFs1c00D5Vc3+jKjLr+s7eBjARHPTsJN+wvrQ7Egx+wc9YyVCGDv8csqFWt8Ej4pyLhJfWkt09yv1EA/CFuXyqePrxvzeZtm+YJSYKZDJszi/yX92/VxNgRrtDIbiwUr557N9KffuVCuOLkkIgqm2wN4+GBHH+bi3KqfZ9lp/vItY/8XfitueKZZ9uCvTZ1+YMTC8T8T1Fy+cCxMhRsIn9GMjxyaeiUe1mmETbbAD3OkOZbQmvc29XuvI5zdrp/pZF+lADa3W7is9abHTe1x6+OhSxS+6VUnbN25A+N9zTw1+8hHl77EI7QQKk9Okj6PKEQ5R//4w4F5W/gbD8Rs7w1CjykRV0T7q9+t1KqMCvmO8aUcpMnRTV/xIuEAmnW6ahkplXQkyJCs6ZVxHl1PKWCZnCiabexypyLP/z94vv1cCeMMhbuKX9kuHGz9QZP47J3Cd3FUyKfMouz8kRBGsmxYf1ANtTK4D34dXJC1lJ31kPYi4T9uzZNzNwwE2MeBLDuZTIqsYBO/F1MonEqAEDcprs6HZMF1tObN7VgtsCafG8W7pkgUt4SbEj7dCbOhgPbg9TI/WbedLKq2iMKK3SrzDTjsv500TE1mkYUjUYkejlm1lb/gUhO2t+3Uq/TnzUqQYxJfA7ACXQSHQ=
  bucket: dictionary-artifacts
  local-dir: artifacts
  upload-dir: rerf_dictionary/$TRAVIS_BRANCH
  skip_cleanup: true
  on:
    repo: uc-cdis/rerf_dictionary
    all_branches: true
