## Get the latest version of Dictionarytool
cd /Users/christopher/Documents/GitHub/cgmeyer/Dictionarytool
git checkout master
git pull upstream master
git commit -a -m "updates"
git push origin master
#git reset --hard upstream/master


################################################################################
################################################################################
##### Get VA dictionary nodes
################################################################################
# Create the TSVs from YAML schemas
tool="/Users/christopher/Documents/GitHub/cgmeyer/Dictionarytool/testing/run/yaml2tsv.py"
yaml_in="/Users/christopher/Documents/GitHub/occ-data/bpadictionary/gdcdictionary/schemas/"
tsv_out="/Users/christopher/Documents/GitHub/occ-data/bpadictionary/gdcdictionary/tsvs/"
dd_name="bpa"

rm -r -f -- $tsv_out
python $tool -y $yaml_in -t $tsv_out -d $dd_name

################################################################################
################################################################################
##### Get BloodPAC dictionary nodes
################################################################################
# Create the TSVs from YAML schemas
tool="/Users/christopher/Documents/GitHub/cgmeyer/Dictionarytool/testing/run/yaml2tsv.py"
yaml_in="/Users/christopher/Documents/GitHub/uc-cdis/vadictionary/gdcdictionary/schemas/"
tsv_out="/Users/christopher/Documents/GitHub/uc-cdis/vadictionary/gdcdictionary/tsvs/"
dd_name="va"

rm -r -f -- $tsv_out
python $tool -y $yaml_in -t $tsv_out -d $dd_name

################################################################################
################################################################################
##### RERF Commons Dict
################################################################################

cd /Users/christopher/Documents/GitHub/uc-cdis/rerf_dictionary/
git checkout develop
git pull origin develop
git fetch origin develop

# Create the TSVs from YAML schemas
tool="/Users/christopher/Documents/GitHub/cgmeyer/Dictionarytool/testing/run/yaml2tsv.py"
yaml_in="/Users/christopher/Documents/GitHub/uc-cdis/rerf_dictionary/gdcdictionary/schemas/"
tsv_out="/Users/christopher/Documents/GitHub/uc-cdis/rerf_dictionary/gdcdictionary/tsvs/"
dd_name="rerf"

rm -r -f -- $tsv_out
python $tool -y $yaml_in -t $tsv_out -d $dd_name

# Now I will convert the TSVs generated by the Dictionarytool back to YAML files:
# the command for removing enumDefs is -terms et; if you want all terms removed its -terms at
tool="/Users/christopher/Documents/GitHub/cgmeyer/Dictionarytool/testing/run/tsv2yaml.py"
nodes="${tsv_out}nodes_${dd_name}.tsv"
variables="${tsv_out}variables_${dd_name}.tsv"
outdir="${tsv_out}back2yamls/"
python $tool -terms et -nodes $nodes -var $variables -out $outdir

# Now replace the yamls and make a pull request to test
mv ${outdir}/*.yaml $yaml_in
git add -A
git commit -a -m "test"
git push origin test
